
package GUI;

import DataPegawai.*;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author Rita
 */
public class FormView extends javax.swing.JFrame {
	Jadwal jadwal;
	public static DaftarKaryawan kar;
	Setting setting;
	Bulan dataBulan;
	
    /**
     * Creates new form FormView
     */
    public FormView() {
        jadwal = new Jadwal();
		kar = new DaftarKaryawan();
		setting = new Setting();
		dataBulan = new Bulan();
		initComponents();
		Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
		this.setTitle("Employee Management");
		
		tableDataPegawai.setModel(showDataPegawai().getModel());
		ButtonColumn buttonColumn = new ButtonColumn(tableDataPegawai, 5);
		showSettingView();
		bulanGajiOnChanged();
		
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableGaji = new javax.swing.JTable();
        bulanGaji = new javax.swing.JComboBox();
        editGaji = new javax.swing.JButton();
        viewDataPegawai = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableDataPegawai = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableJadwalPagi = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tableJadwalMalam = new javax.swing.JTable();
        generateJadwal = new javax.swing.JButton();
        printToPdf = new javax.swing.JButton();
        namaFile = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jumlahKasir = new javax.swing.JTextField();
        jumlahCuci = new javax.swing.JTextField();
        jumlahMasak = new javax.swing.JTextField();
        jumlahBartender = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jumlahHall = new javax.swing.JTextField();
        buttonSetting = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        traineeKasir = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        traineeCuci = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        traineeMasak = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        traineeBartender = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        traineeHall = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        nontraineeKasir = new javax.swing.JTextField();
        nontraineeCuci = new javax.swing.JTextField();
        nontraineeMasak = new javax.swing.JTextField();
        nontraineeBartender = new javax.swing.JTextField();
        nontraineeHall = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nohp = new javax.swing.JTextField();
        alamat = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        seninpagi = new javax.swing.JCheckBox();
        seninmalam = new javax.swing.JCheckBox();
        selasamalam = new javax.swing.JCheckBox();
        selasapagi = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        rabupagi = new javax.swing.JCheckBox();
        rabumalam = new javax.swing.JCheckBox();
        kamismalam = new javax.swing.JCheckBox();
        kamispagi = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jumatpagi = new javax.swing.JCheckBox();
        jumatmalam = new javax.swing.JCheckBox();
        sabtumalam = new javax.swing.JCheckBox();
        sabtupagi = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        minggupagi = new javax.swing.JCheckBox();
        minggumalam = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        posisi = new javax.swing.JComboBox();
        jLabel28 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Gaji Bulan");

        tableGaji.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nama", "Absensi", "Presensi", "Rate Gaji", "Gaji Total"
            }
        ));
        jScrollPane2.setViewportView(tableGaji);

        bulanGaji.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "pilih bulan", "Januari", "Febuari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));

        editGaji.setText("Ubah");
        editGaji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editGajiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bulanGaji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(editGaji)
                .addGap(54, 54, 54))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(bulanGaji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editGaji))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(240, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Daftar Gaji", jPanel2);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Data Pegawai");

        DaftarKaryawan datakar = new DaftarKaryawan();
        Object[][] tempdatakar = new Object [datakar.listKaryawan.size()][7];
        for(int i = 0 ; i<datakar.listKaryawan.size();i++){
            tempdatakar[i][0]= i+11;
            tempdatakar[i][1]=datakar.getKaryawanByID(i+11).getNama();
            tempdatakar[i][2]=datakar.getKaryawanByID(i+11).getAlamat();
            tempdatakar[i][3]=datakar.getKaryawanByID(i+11).getNo_hp();
            tempdatakar[i][4]=datakar.getKaryawanByID(i+11).getId_rate_gaji();
        }
        tableDataPegawai.setModel(new javax.swing.table.DefaultTableModel(
            tempdatakar,
            new String [] {
                "NIP","Nama", "Alamat", "No HP", "ID Gaji", "Hari"
            }
        )  );
        tableDataPegawai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDataPegawaiMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tableDataPegawai);

        jButton3.setText("Edit Field");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout viewDataPegawaiLayout = new javax.swing.GroupLayout(viewDataPegawai);
        viewDataPegawai.setLayout(viewDataPegawaiLayout);
        viewDataPegawaiLayout.setHorizontalGroup(
            viewDataPegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewDataPegawaiLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel16)
                .addGap(91, 91, 91)
                .addComponent(jButton3)
                .addComponent(jButton4)
                .addGap(21,21,21)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(viewDataPegawaiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        viewDataPegawaiLayout.setVerticalGroup(
            viewDataPegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewDataPegawaiLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(viewDataPegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Daftar Pegawai", viewDataPegawai);
        viewDataPegawai.getAccessibleContext().setAccessibleName("");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("Jadwal Bulan");

        jLabel18.setText("Pagi");

        tableJadwalPagi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Senin", "Selasa", "Rabu", "Kamis", "Jumat", "Sabtu", "Minggu"
            }
        ));
        jScrollPane4.setViewportView(tableJadwalPagi);

        jLabel19.setText("Malam");

        tableJadwalMalam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Senin", "Selasa", "Rabu", "Kamis", "Jumat", "Sabtu", "Minggu"
            }
        ));
        jScrollPane5.setViewportView(tableJadwalMalam);

        generateJadwal.setText("Buat Jadwal");
        generateJadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateJadwalActionPerformed(evt);
            }
        });

        printToPdf.setText("Simpan di PDF");
        printToPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printToPdfActionPerformed(evt);
            }
        });

        jLabel34.setText("Nama File :");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel19)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel17))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel34)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(namaFile)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(printToPdf)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(generateJadwal)
                                .addGap(25, 25, 25)))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(generateJadwal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34)
                    .addComponent(printToPdf))
                .addGap(94, 94, 94))
        );

        jTabbedPane1.addTab("Daftar Jadwal", jPanel4);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setText("Pengaturan");

        jLabel21.setText("Jumlah Minimal Kasir : ");

        jLabel22.setText("Jumlah Minimal Cuci : ");

        jLabel23.setText("Jumlah Minimal Masak : ");

        jLabel24.setText("Jumlah Minimal Bartender : ");

        jLabel25.setText("Jumlah Minimal Hall : ");

        jLabel26.setText("Rate Gaji Trainee : ");

        jLabel27.setText("Rate Gaji Non-Trainee : ");

        jLabel29.setText("pegawai");

        jLabel30.setText("pegawai");

        jLabel31.setText("pegawai");

        jLabel32.setText("pegawai");

        jLabel33.setText("pegawai");

        buttonSetting.setText("OK");
        buttonSetting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSettingActionPerformed(evt);
            }
        });

        jLabel37.setText("Kasir");

        jLabel38.setText("Rp.");

        jLabel39.setText("Cuci");

        jLabel40.setText("Rp.");

        jLabel41.setText("Masak");

        jLabel42.setText("Rp.");

        jLabel43.setText("Bartender");

        jLabel44.setText("Rp.");

        jLabel45.setText("Hall");

        jLabel46.setText("Rp.");

        jLabel47.setText("Kasir");

        jLabel48.setText("Cuci");

        jLabel49.setText("Masak");

        jLabel50.setText("Bartender");

        jLabel51.setText("Hall");

        jLabel52.setText("Rp.");

        jLabel53.setText("Rp.");

        jLabel54.setText("Rp.");

        jLabel55.setText("Rp.");

        jLabel56.setText("Rp.");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel50)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel54)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nontraineeBartender, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel49)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel55)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nontraineeMasak, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel48)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel56)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nontraineeCuci, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel47)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel52)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nontraineeKasir, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel51)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel53)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nontraineeHall, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(buttonSetting)
                .addGap(40, 40, 40))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel21)
                                            .addComponent(jLabel22)
                                            .addComponent(jLabel23)
                                            .addComponent(jLabel24)
                                            .addComponent(jLabel25))
                                        .addGap(55, 55, 55)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jumlahKasir, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                                            .addComponent(jumlahCuci)
                                            .addComponent(jumlahMasak)
                                            .addComponent(jumlahBartender)
                                            .addComponent(jumlahHall))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel33)
                                            .addComponent(jLabel32)
                                            .addComponent(jLabel31)
                                            .addComponent(jLabel30)
                                            .addComponent(jLabel29))))
                                .addGap(0, 144, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel43)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel44)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(traineeBartender, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel41)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel42)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(traineeMasak, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel39)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel40)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(traineeCuci, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel37)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel38)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(traineeKasir, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel45)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel46)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(traineeHall, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(103, 103, 103))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jumlahKasir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jumlahCuci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jumlahMasak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jumlahBartender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jumlahHall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(traineeKasir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel38))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel40)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel39)
                        .addComponent(traineeCuci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel42)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(traineeMasak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel41)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel44)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(traineeBartender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel43)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel46)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(traineeHall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel45)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel27)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonSetting)
                        .addContainerGap())
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel47)
                            .addComponent(nontraineeKasir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel52))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel56)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel48)
                                .addComponent(nontraineeCuci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel55)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(nontraineeMasak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel49)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel54)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(nontraineeBartender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel50)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel53)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(nontraineeHall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel51)))
                        .addContainerGap(44, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("Pengaturan", jPanel5);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Formulir Pengisian Data Pegawai");

        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });

        jLabel2.setText("Nama  : ");

        jLabel3.setText("No. HP:");

        jLabel4.setText("Alamat :");

        jLabel5.setText("Hari :");

        jLabel9.setText("Senin");

        seninpagi.setText("Pagi");
        seninpagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seninpagiActionPerformed(evt);
            }
        });

        seninmalam.setText("Malam");
        seninmalam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seninmalamActionPerformed(evt);
            }
        });

        selasamalam.setText("Malam");

        selasapagi.setText("Pagi");
        selasapagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selasapagiActionPerformed(evt);
            }
        });

        jLabel8.setText("Selasa");

        jLabel10.setText("Rabu");

        rabupagi.setText("Pagi");
        rabupagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rabupagiActionPerformed(evt);
            }
        });

        rabumalam.setText("Malam");
        rabumalam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rabumalamActionPerformed(evt);
            }
        });

        kamismalam.setText("Malam");

        kamispagi.setText("Pagi");
        kamispagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kamispagiActionPerformed(evt);
            }
        });

        jLabel11.setText("Kamis");

        jLabel12.setText("Jumat");

        jumatpagi.setText("Pagi");
        jumatpagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumatpagiActionPerformed(evt);
            }
        });

        jumatmalam.setText("Malam");
        jumatmalam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumatmalamActionPerformed(evt);
            }
        });

        sabtumalam.setText("Malam");

        sabtupagi.setText("Pagi");
        sabtupagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sabtupagiActionPerformed(evt);
            }
        });

        jLabel13.setText("Sabtu");

        jLabel14.setText("Minggu");

        minggupagi.setText("Pagi");
        minggupagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minggupagiActionPerformed(evt);
            }
        });

        minggumalam.setText("Malam");
        minggumalam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minggumalamActionPerformed(evt);
            }
        });

        jButton1.setText("Simpan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        posisi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cuci", "Masak", "Bartender", "Hall", "Kasir" }));
        posisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posisiActionPerformed(evt);
            }
        });

        jLabel28.setText("Posisi : ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nohp, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(minggupagi)
                            .addGap(18, 18, 18)
                            .addComponent(minggumalam))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(8, 8, 8)
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel9)
                                    .addGap(23, 23, 23))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel11)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel12))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(1, 1, 1)
                                            .addComponent(jLabel14)))
                                    .addGap(18, 18, 18)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(seninpagi)
                                    .addGap(18, 18, 18)
                                    .addComponent(seninmalam))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(selasapagi)
                                    .addGap(18, 18, 18)
                                    .addComponent(selasamalam))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(rabupagi)
                                    .addGap(18, 18, 18)
                                    .addComponent(rabumalam))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(kamispagi)
                                    .addGap(18, 18, 18)
                                    .addComponent(kamismalam))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jumatpagi)
                                    .addGap(18, 18, 18)
                                    .addComponent(jumatmalam))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(sabtupagi)
                                    .addGap(18, 18, 18)
                                    .addComponent(sabtumalam))))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addComponent(jLabel28)
                            .addGap(28, 28, 28)
                            .addComponent(posisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jButton1))
                    .addComponent(jLabel1))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(seninpagi)
                        .addComponent(seninmalam)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nohp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(49, 49, 49)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selasapagi)
                    .addComponent(selasamalam)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(rabupagi)
                    .addComponent(rabumalam))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(kamispagi))
                    .addComponent(kamismalam))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jumatpagi)
                        .addComponent(jumatmalam)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sabtumalam)
                    .addComponent(sabtupagi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minggupagi)
                    .addComponent(minggumalam))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(posisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addGap(28, 28, 28)
                .addComponent(jButton1)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Formulir Data Pegawai", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void minggumalamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minggumalamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minggumalamActionPerformed

    private void minggupagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minggupagiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minggupagiActionPerformed

    private void sabtupagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sabtupagiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sabtupagiActionPerformed

    private void jumatmalamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumatmalamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumatmalamActionPerformed

    private void jumatpagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumatpagiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumatpagiActionPerformed

    private void kamispagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kamispagiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kamispagiActionPerformed

    private void rabumalamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rabumalamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rabumalamActionPerformed

    private void rabupagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rabupagiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rabupagiActionPerformed

    private void selasapagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selasapagiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selasapagiActionPerformed

    private void seninmalamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seninmalamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seninmalamActionPerformed

    private void seninpagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seninpagiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seninpagiActionPerformed

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    private void generateJadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateJadwalActionPerformed
		jadwal.generateJadwal();
		tableJadwalPagi.setModel(createJadwalTable(0).getModel());
		tableJadwalMalam.setModel(createJadwalTable(1).getModel());
    }//GEN-LAST:event_generateJadwalActionPerformed

    private JTable showDataPegawai(){
        Object[][] tempdatakar = new Object [kar.listKaryawan.size()][6];
        for(int i = 0 ; i<kar.listKaryawan.size();i++){
            tempdatakar[i][0]= kar.listKaryawan.get(i).getNip();
            tempdatakar[i][1]=kar.listKaryawan.get(i).getNama();
            tempdatakar[i][2]=kar.listKaryawan.get(i).getAlamat();
            tempdatakar[i][3]=kar.listKaryawan.get(i).getNo_hp();
//            tempdatakar[i][4]=setting.getGaji(kar.listKaryawan.get(i).getId_rate_gaji()).getNominal();
			tempdatakar[i][4]=kar.listKaryawan.get(i).getId_rate_gaji();
			tempdatakar[i][5]="lihat hari available";
        }
        String[] columnNames = {
                "NIP","Nama", "Alamat", "No HP", "ID Gaji", "Hari"
            };
        return new JTable(tempdatakar, columnNames);
        
    }
    
	/**
	 * Membuat tabel jadwal berdasarkan jadwal yang sudah dibuat
	 * @param inputJam 0 untuk pagi, 1 untuk malam
	 * @return tabel jadwal bertipe JTable
	 */
	private JTable createJadwalTable(int inputJam){
		Object[][] data = new Object[jadwal.getTotalKaryawanButuh()][7];
		int i;
		int j=0;
		for(int sk=inputJam;sk<14;sk=sk+2){
			for(i=0;i<jadwal.getJadwalKerja().get(sk).getListOfKaryawan().size();i++){
				System.out.println(i+" "+j);
				data[i][j] = kar.getKaryawanByID(jadwal.getJadwalKerja().get(sk).getListOfKaryawan().get(i)).getNama();
			}
			j++;
		}
		
        String[] columnNames = {
            "Senin","Selasa","Rabu","Kamis","Jumat","Sabtu","Minggu"
            };
        return new JTable(data, columnNames);
	}
	
    private void tableDataPegawaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDataPegawaiMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tableDataPegawaiMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String name=JOptionPane.showInputDialog("Enter Info");
        tableDataPegawai.getModel().setValueAt(name,tableDataPegawai.getSelectedRow(),tableDataPegawai.getSelectedColumn());
        System.out.println(tableDataPegawai.getSelectedRow()+" "+tableDataPegawai.getSelectedColumn());
        String nama, alamat, noHp;
        int nip, idGaji;
            nip = (int)tableDataPegawai.getValueAt(tableDataPegawai.getSelectedRow(), 0);
            nama = tableDataPegawai.getValueAt(tableDataPegawai.getSelectedRow(), 1).toString();
            alamat = tableDataPegawai.getValueAt(tableDataPegawai.getSelectedRow(), 2).toString();
            noHp = tableDataPegawai.getValueAt(tableDataPegawai.getSelectedRow(), 3).toString();
            idGaji = (int)tableDataPegawai.getValueAt(tableDataPegawai.getSelectedRow(), 4);
            System.out.println(nip+"   "+nama);
       kar.editKaryawanByID(new Karyawan(nama,nip,noHp,alamat,idGaji,null));
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int nip;
            nip = (int)tableDataPegawai.getValueAt(tableDataPegawai.getSelectedRow(), 0);
        kar.deleteKaryawanByID(nip);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void printToPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printToPdfActionPerformed
        String judul = namaFile.getText();
		if(judul != null && !judul.equals("")){
			Object temp;
			String res;
			int i,j;

			String jadwalPagi = "\n\nJadwal Pagi\n";
			for(i=0;i<7;i++){
				temp = tableJadwalPagi.getColumnName(i);
				res = temp.toString();
				while(res.length() < 10){
					res += " ";
				}
				jadwalPagi += res;
			}
			jadwalPagi += "\n";
			for(i=0;i<jadwal.getTotalKaryawanButuh();i++){
				for(j=0;j<7;j++){
					temp = tableJadwalPagi.getValueAt(i,j);
					if(temp == null){
						temp = "";
					}
					res = temp.toString();
					while(res.length() < 10){
						res += " ";
					}
					jadwalPagi += res;
				}
				jadwalPagi += "\n";
			}

			String jadwalMalam = "\nJadwal Malam\n";
			for(i=0;i<7;i++){
				temp = tableJadwalMalam.getColumnName(i);
				res = temp.toString();
				while(res.length() < 10){
					res += " ";
				}
				jadwalMalam += res;
			}
			jadwalMalam += "\n";
			for(i=0;i<jadwal.getTotalKaryawanButuh();i++){
				for(j=0;j<7;j++){
					temp = tableJadwalMalam.getValueAt(i,j);
					if(temp == null){
						temp = "";
					}
					res = temp.toString();
					while(res.length() < 10){
						res += " ";
					}
					jadwalMalam += res;
				}
				jadwalMalam += "\n";
			}

			Document document = new Document();
			try
			{
				PdfWriter writer = PdfWriter.getInstance(document, new FileOutputStream(judul+".pdf"));
				document.open();
			Font theFont = FontFactory.getFont("COURIER", 12);
				document.add(new Paragraph(judul, theFont));
				document.add(new Paragraph(jadwalPagi, theFont));
				document.add(new Paragraph(jadwalMalam, theFont));
				document.close();
				writer.close();
				JOptionPane.showMessageDialog(null, "Print to PDF Finished");
			} catch (DocumentException e)
			{
				e.printStackTrace();
			} catch (FileNotFoundException e)
			{
				e.printStackTrace();
			}
		} else {
			JOptionPane.showMessageDialog(null, "Masukkan nama file");
		}
    }//GEN-LAST:event_printToPdfActionPerformed

	private JTable createGajiTable(){
		System.out.println("-create gaji table-");
		Object[][] data = null;
		String[] columnNames = {
				"NIP","Nama","Status","Posisi","Absensi","Presensi","Rate Gaji","Gaji Total"
				};
		if(bulanGaji.getSelectedIndex() != 0){
			int indexBulan = bulanGaji.getSelectedIndex();
			dataBulan.setNomor(indexBulan);
			System.out.println("bulan="+indexBulan);
			dataBulan.setDaftarKaryawanByBulan();
			System.out.println("list pegawai size="+dataBulan.getListPegawai().size());
			data = new Object[dataBulan.getListPegawai().size()][8];
			int i;
			int j=0;
			for(i=0;i<dataBulan.getListPegawai().size();i++){
				data[i][0] = dataBulan.getListPegawai().get(i).getNip();
				data[i][1] = dataBulan.getListPegawai().get(i).getNama();
				data[i][2] = setting.getGaji(dataBulan.getListPegawai().get(i).getId_rate_gaji()).getStatus();
				data[i][3] = setting.getGaji(dataBulan.getListPegawai().get(i).getId_rate_gaji()).getPekerjaan();
				data[i][4] = dataBulan.getListPegawai().get(i).getAbsensi();
				data[i][5] = dataBulan.getListPegawai().get(i).getPresensi();
				data[i][6] = setting.getGaji(dataBulan.getListPegawai().get(i).getId_rate_gaji()).getNominal();
				data[i][7] = dataBulan.getListPegawai().get(i).getGajibulanan();
			}
		}
		return new JTable(data, columnNames);
	}
	
	private void bulanGajiOnChanged(){
		bulanGaji.addActionListener (new ActionListener () {
			public void actionPerformed(ActionEvent e) {
				if(bulanGaji.getSelectedIndex() != 0){
					tableGaji.setModel(createGajiTable().getModel());
				}
			}
		});
	}
	
	
	private void showSettingView(){
		setting.getSettingData();
		jumlahCuci.setText(setting.getJumlahPegawaiPerKerja().get(0).toString());
		jumlahMasak.setText(setting.getJumlahPegawaiPerKerja().get(1).toString());
		jumlahBartender.setText(setting.getJumlahPegawaiPerKerja().get(2).toString());
		jumlahHall.setText(setting.getJumlahPegawaiPerKerja().get(3).toString());
		jumlahKasir.setText(setting.getJumlahPegawaiPerKerja().get(4).toString());
		traineeCuci.setText(String.valueOf(setting.getRateGaji().get(0).getNominal()));
		traineeMasak.setText(String.valueOf(setting.getRateGaji().get(1).getNominal()));
		traineeBartender.setText(String.valueOf(setting.getRateGaji().get(2).getNominal()));
		traineeHall.setText(String.valueOf(setting.getRateGaji().get(3).getNominal()));
		traineeKasir.setText(String.valueOf(setting.getRateGaji().get(4).getNominal()));
		nontraineeCuci.setText(String.valueOf(setting.getRateGaji().get(5).getNominal()));
		nontraineeMasak.setText(String.valueOf(setting.getRateGaji().get(6).getNominal()));
		nontraineeBartender.setText(String.valueOf(setting.getRateGaji().get(7).getNominal()));
		nontraineeHall.setText(String.valueOf(setting.getRateGaji().get(8).getNominal()));
		nontraineeKasir.setText(String.valueOf(setting.getRateGaji().get(9).getNominal()));
	}
	
    private void buttonSettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSettingActionPerformed
		setting.setSettingInDB(Integer.valueOf(jumlahCuci.getText()), 
				Integer.valueOf(jumlahMasak.getText()), 
				Integer.valueOf(jumlahHall.getText()), 
				Integer.valueOf(jumlahBartender.getText()), 
				Integer.valueOf(jumlahKasir.getText()));
		List<Integer> rateGajiInput = new ArrayList<>();
		rateGajiInput.add(Integer.valueOf(traineeCuci.getText()));
		rateGajiInput.add(Integer.valueOf(traineeMasak.getText()));
		rateGajiInput.add(Integer.valueOf(traineeBartender.getText()));
		rateGajiInput.add(Integer.valueOf(traineeHall.getText()));
		rateGajiInput.add(Integer.valueOf(traineeKasir.getText()));
		rateGajiInput.add(Integer.valueOf(nontraineeCuci.getText()));
		rateGajiInput.add(Integer.valueOf(nontraineeMasak.getText()));
		rateGajiInput.add(Integer.valueOf(nontraineeBartender.getText()));
		rateGajiInput.add(Integer.valueOf(nontraineeHall.getText()));
		rateGajiInput.add(Integer.valueOf(nontraineeKasir.getText()));
		setting.setRateGajiInDB(rateGajiInput);
		showSettingView();
    }//GEN-LAST:event_buttonSettingActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           
        String namabaru = nama.getText();
        String alamatbaru = alamat.getText();
        String nohpbaru = nohp.getText();
        boolean seninpagib= seninpagi.isSelected();
        boolean seninmalamb= seninmalam.isSelected();
        boolean selasapagib= selasapagi.isSelected();
        boolean selasamalamb= selasamalam.isSelected();
        boolean rabupagib= rabupagi.isSelected();
        boolean rabumalamb= rabumalam.isSelected();
        boolean kamispagib= kamispagi.isSelected();
        boolean kamismalamb= kamismalam.isSelected();
        boolean jumatpagib= jumatpagi.isSelected();
        boolean jumatmalamb= jumatmalam.isSelected();
        boolean sabtupagib= sabtupagi.isSelected();
        boolean sabtumalamb= sabtumalam.isSelected();
        boolean minggupagib= minggupagi.isSelected();
        boolean minggumalamb= minggumalam.isSelected();
        int posisibaru = 21 + posisi.getSelectedIndex();
        
        List<ShiftKerja> listkerja = new ArrayList<>();
        if(seninpagib){
            listkerja.add(new ShiftKerja(1, "pagi", "senin"));
        }
        if(seninmalamb){
            listkerja.add(new ShiftKerja(2,"malam", "senin"));
        }
        if(selasapagib){
            listkerja.add(new ShiftKerja(3, "pagi", "selasa"));
        }
        if(selasamalamb){
            listkerja.add(new ShiftKerja(4,"malam", "selasa"));
        }
        if(rabupagib){
            listkerja.add(new ShiftKerja(5, "pagi", "rabu"));
        }
        if(rabumalamb){
            listkerja.add(new ShiftKerja(6,"malam", "rabu"));
        }
        if(kamispagib){
            listkerja.add(new ShiftKerja(7, "pagi", "kamis"));
        }
        if(kamismalamb){
            listkerja.add(new ShiftKerja(8,"malam", "kamis"));
        }
        if(jumatpagib){
            listkerja.add(new ShiftKerja(9, "pagi", "jumat"));
        }
        if(jumatmalamb){
            listkerja.add(new ShiftKerja(10,"malam", "jumat"));
        }
        if(sabtupagib){
            listkerja.add(new ShiftKerja(11, "pagi", "sabtu"));
        }
        if(sabtumalamb){
            listkerja.add(new ShiftKerja(12,"malam", "sabtu"));
        }
        if(minggupagib){
            listkerja.add(new ShiftKerja(13, "pagi", "minggu"));
        }
        if(minggumalamb){
            listkerja.add(new ShiftKerja(14,"malam", "minggu"));
        }

        Karyawan newkaryawan = new Karyawan(namabaru,0, nohpbaru, alamatbaru,posisibaru,listkerja);
        kar.addKaryawan(newkaryawan);
        tableDataPegawai.setModel(showDataPegawai().getModel());
    }//GEN-LAST:event_jButton1ActionPerformed


    private void posisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posisiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_posisiActionPerformed

    private void editGajiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editGajiActionPerformed
        System.out.println(tableGaji.getSelectedRow()+" "+tableDataPegawai.getSelectedColumn());
       
        int nip, absen,presen;
		if(tableGaji.getSelectedColumn() == 1  || tableGaji.getSelectedColumn() == 2  ){
			String name=JOptionPane.showInputDialog("Enter Info");
			tableGaji.getModel().setValueAt(name,tableGaji.getSelectedRow(),tableGaji.getSelectedColumn());
            nip = (int)tableGaji.getValueAt(tableGaji.getSelectedRow(), 0);
            absen = (int)tableGaji.getValueAt(tableGaji.getSelectedRow(), 4);
            presen = (int)tableGaji.getValueAt(tableGaji.getSelectedRow(), 5);
			dataBulan.updatePresensi(nip,presen,absen);
		}
		
    }//GEN-LAST:event_editGajiActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat;
    private javax.swing.JComboBox bulanGaji;
    private javax.swing.JButton buttonSetting;
    private javax.swing.JButton editGaji;
    private javax.swing.JButton generateJadwal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JCheckBox jumatmalam;
    private javax.swing.JCheckBox jumatpagi;
    private javax.swing.JTextField jumlahBartender;
    private javax.swing.JTextField jumlahCuci;
    private javax.swing.JTextField jumlahHall;
    private javax.swing.JTextField jumlahKasir;
    private javax.swing.JTextField jumlahMasak;
    private javax.swing.JCheckBox kamismalam;
    private javax.swing.JCheckBox kamispagi;
    private javax.swing.JCheckBox minggumalam;
    private javax.swing.JCheckBox minggupagi;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField namaFile;
    private javax.swing.JTextField nohp;
    private javax.swing.JTextField nontraineeBartender;
    private javax.swing.JTextField nontraineeCuci;
    private javax.swing.JTextField nontraineeHall;
    private javax.swing.JTextField nontraineeKasir;
    private javax.swing.JTextField nontraineeMasak;
    private javax.swing.JComboBox posisi;
    private javax.swing.JButton printToPdf;
    private javax.swing.JCheckBox rabumalam;
    private javax.swing.JCheckBox rabupagi;
    private javax.swing.JCheckBox sabtumalam;
    private javax.swing.JCheckBox sabtupagi;
    private javax.swing.JCheckBox selasamalam;
    private javax.swing.JCheckBox selasapagi;
    private javax.swing.JCheckBox seninmalam;
    private javax.swing.JCheckBox seninpagi;
    private javax.swing.JTable tableDataPegawai;
    private javax.swing.JTable tableGaji;
    private javax.swing.JTable tableJadwalMalam;
    private javax.swing.JTable tableJadwalPagi;
    private javax.swing.JTextField traineeBartender;
    private javax.swing.JTextField traineeCuci;
    private javax.swing.JTextField traineeHall;
    private javax.swing.JTextField traineeKasir;
    private javax.swing.JTextField traineeMasak;
    private javax.swing.JPanel viewDataPegawai;
    // End of variables declaration//GEN-END:variables
}
